### ISSUE TITLE
Basic auth no longer supported on new firmware for this camera

### ISSUE THREAD

**Issue by PockyBum522** [jasenmh/pyFoscamLib#4]
I don't know if you're still maintaining this, but I modified your module to use the digest auth that the newer firmwares use. If you want to integrate it into your code, feel free. Thanks!

Link: https://github.com/familab/py_foscam_labcam

**Comment by jasenmh** [comment]
Thank alot! I've been meaning update this for a while now. Now I have even more reason!

**Comment by PockyBum522** [comment]
Awesome! My code probably isn't gorgeous, but it works. Let me know if you
have any questions. Glad to be a kick in the pants.

Also, I got the realm info using your basic auth code, so that's something
I don't have implemented in mine that probably should be there.

--
David Sikes
Owner, Sikes PC Repair

Cell/Work: (407) 463-2925
Mail: David@SikesPC.com
http://www.SikesPC.com
